--CREATE DATABASE CarComparison;

CREATE TABLE Car 
(
	Variant VARCHAR(150) PRIMARY KEY,
	ReleaseYear DATE,
	FuelUsagePerKM FLOAT NOT NULL,
	Price FLOAT NOT NULL,
	MName VARCHAR(50) NOT NULL,
	BName VARCHAR(30) NOT NULL,
	FuelName VARCHAR(10) NOT NULL
)
